name: banuba_arcloud_example
description: Demonstrates how to use the Banuba ARCloud plugin.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true