name: banuba_arcloud_example
description: Demonstrates how to use the Banuba ARCloud plugin.

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  banuba_arcloud:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/effect/download.png